//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleCount
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int VisitorsId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string IdType { get; set; }
        public string IdNum { get; set; }
        public string vehicle { get; set; }
        public string Contact { get; set; }
        public string Purpose { get; set; }
        public string status { get; set; }
        public System.DateTime checkinTime { get; set; }
    }
}
